### ISSUE TITLE
Empty string throws error

### ISSUE THREAD

**Issue by AdamBrodzinski** [ScottONeal/xfdf#2]
I was just wondering what the expected behavior is for empty string values? Currently it throws an error,  `addField() called, but no value argument supplied` which is fine if that's the intention but I thought i'd bring it up just in case. 

I'm planning on just filtering the object values before passing into `fromJSON`.

Example to replicate:

``` javascript
new Xfdf().fromJSON({fields: {firstName: 'adam'}}).generate()
// returns string

new Xfdf().fromJSON({fields: {firstName: 'adam', foo: ''}}).generate()
// throws error:

/*
Error: addField() called, but no value argument supplied
    at XFDF.addField (/Users/adam/projects/foo/bar/.meteor/local/isopacks/npm-container/npm/node_modules/xfdf/index.js:32:11)
*/
```

Btw thanks again for creating this, huge timesaver! :beers:

**Comment by ScottONeal** [comment]
I suppose it should allow empty strings, specially since a load from JSON might contain it, as in your use case.

**Comment by ScottONeal** [comment]
Okay, just commited 3aebdbbf2a43b8dfa91da456b9c550642306f876

This will allow you to add an empty string to a xfdf file.

**Comment by AdamBrodzinski** [comment]
Thanks for the quick fix!
