### ISSUE TITLE
NSP Check - updating dependencies

### ISSUE THREAD

**Issue by nate-vukovich** [ScottONeal/xfdf#4]
After a NSP check of pdf-form-fill of the latest version (0.2.1) package vurns are found in this module.

Resolve:

- update lodash to 4.17.10
- update xmlbuilder to 10.0.0

Test run same as before.

Would love to PR this to merge to master to get pass the nsp check.

Regards.

**Comment by ScottONeal** [comment]
Sorry for the crazy long delay, I've updated all of the dependencies and published `1.0.0`: https://www.npmjs.com/package/xfdf
